server:
  port: 9001

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/purgil_user_db
    username: purgil_master
    password: kuaile2515!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: user_schema

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka