### 이메일 로그인
POST {{user-service-url}}/api/user/login/email
Content-Type: application/json

{
  "email": "tmdghks2515@naver.com",
  "password": "qwe123!"
}


### 이메일 회원가입
POST {{user-service-url}}/api/user/register/email
Content-Type: application/json

{
  "email": "tmdghks2518@naver.com",
  "password": "qwe123!",
  "name": "임승환4"
}
